### ISSUE TITLE
[FR] Add options for maximum users

### ISSUE THREAD

**Issue by EvasiveXkiller** [Maxisthemoose/discord-uno#4]
Is it able to have more options when creating the game?

For examaple: 
```
const discordUNO = new DiscordUNO({
    maxPlayers: 100,
    autoStart: false,
});
```
The host must explicitly start the game instead of auto starting too.

Thanks!

**Comment by seasaltsaige** [comment]
I will see what I can do in the future! I'm currently working on other things, but I'll keep this in mind for sure

**Comment by EvasiveXkiller** [comment]
Thanks!
